# Default values for gtp-proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

listen:
  interface: lo
  ipAddr: 127.0.0.1

proxySocket:
  interface: lo
  ipAddr: 127.0.0.2

pgw:
  ipAddr: 127.0.0.1

httpApi:
  ipAddr: 0.0.0.0
  port: 8000

cpNode:
  image: ergw/ergw-gtp-c-node
  imagePullPolicy: Always

dpNode:
  image: ergw/ergw-gtp-u-edp
  imagePullPolicy: Always

logLevel: debug

vxlanController:
  enabled: false
  vxlan: lan0

initConfig: {}
# - ip a add 192.168.12.10/24
# - ip r add 192.168.77.0/24 via 192.168.12.1

nodeSelector: {}

tolerations: []

affinity: {}
