apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gtp-proxy
  labels:
    app: gtp-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtp-proxy
  template:
    metadata:
      labels:
        app: gtp-proxy
    spec:
      hostname: gtp-proxy
      containers:
      - name: ergw-u-edp
        image: ergw/ergw-gtp-u-edp
        volumeMounts:
        - name: gtp-u-edp-config
          mountPath: /etc/ergw-gtp-u-edp/
      - name: ergw-c-node
        image: ergw/ergw-gtp-c-node:master
        volumeMounts:
        - name: gtp-c-node-config
          mountPath: /etc/ergw-gtp-c-node/
      volumes:
      - name: gtp-u-edp-config
        configMap:
          name: gtp-proxy
          items:
          - key: ergw-gtp-u-edp.config
            path: ergw-gtp-u-edp.config
      - name: gtp-c-node-config
        configMap:
          name: gtp-proxy
          items:
          - key: ergw-gtp-c-node.config
            path: ergw-gtp-c-node.config
