apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gtp-proxy
  labels:
    app: gtp-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtp-proxy
  template:
    metadata:
      labels:
        app: gtp-proxy
    spec:
      containers:
      - name: ergw-u-edp
        image: ergw/ergw-gtp-u-edp
        volumeMounts:
        - name: gtp-u-edp-config
          mountPath: /config/       
      - name: ergw-c-node
        image: ergw/ergw-gtp-c-node
        volumeMounts:
        - name: gtp-c-node-config
          mountPath: /config/
      volumes:
      - name: gtp-u-edp-config
        configMap:
          name: gtp-u-edp-configmap
      - name: gtp-c-node-config
        configMap:
          name: gtp-c-node-configmap
